allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@taiga-ui/addon-charts@5.20.0'
  - '@taiga-ui/addon-mobile@5.20.0'
  - '@taiga-ui/cdk@5.20.0'
  - '@taiga-ui/core@5.20.0'
  - '@taiga-ui/i18n@5.20.0'
  - '@taiga-ui/icons@5.20.0'
  - '@taiga-ui/kit@5.20.0'
  - '@taiga-ui/layout@5.20.0'
  - '@taiga-ui/styles@5.20.0'
  - '@lottiefiles/dotlottie-web@0.79.2'
  - '@angular-devkit/architect@0.2201.5'
  - '@angular-devkit/core@22.1.5'
  - '@angular-devkit/schematics@22.1.5'
  - '@angular/build@22.1.5'
  - '@angular/cdk@22.1.3'
  - '@angular/cli@22.1.5'
  - '@angular/common@22.1.3'
  - '@angular/compiler-cli@22.1.3'
  - '@angular/compiler@22.1.3'
  - '@angular/core@22.1.3'
  - '@angular/forms@22.1.3'
  - '@angular/platform-browser@22.1.3'
  - '@angular/router@22.1.3'
  - '@schematics/angular@22.1.5'
