allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@lottiefiles/dotlottie-web@0.80.0'
  - '@angular-eslint/builder@22.2.0'
  - '@angular-eslint/bundled-angular-compiler@22.2.0'
  - '@angular-eslint/eslint-plugin-template@22.2.0'
  - '@angular-eslint/eslint-plugin@22.2.0'
  - '@angular-eslint/schematics@22.2.0'
  - '@angular-eslint/template-parser@22.2.0'
  - '@angular-eslint/utils@22.2.0'
  - angular-eslint@22.2.0
  - jscpd@5.1.0 || 5.3.3
  - '@capacitor/android@8.5.1'
  - '@capacitor/cli@8.5.1'
  - '@capacitor/core@8.5.1'
  - '@capacitor/ios@8.5.1'
  - '@tiptap/core@3.31.0'
  - '@tiptap/extension-blockquote@3.31.0'
  - '@tiptap/extension-bold@3.31.0'
  - '@tiptap/extension-code@3.31.0'
  - '@tiptap/extension-document@3.31.0'
  - '@tiptap/extension-hard-break@3.31.0'
  - '@tiptap/extension-heading@3.31.0'
  - '@tiptap/extension-italic@3.31.0'
  - '@tiptap/extension-link@3.31.0'
  - '@tiptap/extension-list@3.31.0'
  - '@tiptap/extension-paragraph@3.31.0'
  - '@tiptap/extension-text@3.31.0'
  - '@tiptap/extensions@3.31.0'
  - '@tiptap/pm@3.31.0'
  - '@typescript-eslint/eslint-plugin@8.69.0'
  - '@typescript-eslint/parser@8.69.0'
  - '@typescript-eslint/project-service@8.69.0'
  - '@typescript-eslint/scope-manager@8.69.0'
  - '@typescript-eslint/tsconfig-utils@8.69.0'
  - '@typescript-eslint/type-utils@8.69.0'
  - '@typescript-eslint/types@8.69.0'
  - '@typescript-eslint/typescript-estree@8.69.0'
  - '@typescript-eslint/utils@8.69.0'
  - '@typescript-eslint/visitor-keys@8.69.0'
  - typescript-eslint@8.69.0
  - '@angular-devkit/architect@0.2201.8'
  - '@angular-devkit/core@22.1.8'
  - '@angular-devkit/schematics@22.1.8'
  - '@angular/build@22.1.8'
  - '@angular/cli@22.1.8'
  - '@schematics/angular@22.1.8'
  - jscpd-darwin-arm64@5.3.3
  - jscpd-darwin-x64@5.3.3
  - jscpd-linux-arm64-gnu@5.3.3
  - jscpd-linux-arm64-musl@5.3.3
  - jscpd-linux-x64-gnu@5.3.3
  - jscpd-linux-x64-musl@5.3.3
  - jscpd-windows-arm64-msvc@5.3.3
  - jscpd-windows-x64-msvc@5.3.3
patchedDependencies:
  '@ionic/core@9.0.5': patches/@ionic__core@9.0.5.patch
  '@rdlabo/ionic-theme-ios27@1.1.0': patches/@rdlabo__ionic-theme-ios27@1.1.0.patch
  '@rdlabo/ionic-theme-utils@0.1.1': patches/@rdlabo__ionic-theme-utils@0.1.1.patch
