allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@lottiefiles/dotlottie-web@0.80.0'
  - '@angular-eslint/builder@22.2.0'
  - '@angular-eslint/bundled-angular-compiler@22.2.0'
  - '@angular-eslint/eslint-plugin-template@22.2.0'
  - '@angular-eslint/eslint-plugin@22.2.0'
  - '@angular-eslint/schematics@22.2.0'
  - '@angular-eslint/template-parser@22.2.0'
  - '@angular-eslint/utils@22.2.0'
  - angular-eslint@22.2.0
  - jscpd@5.1.0
  - '@capacitor/android@8.5.1'
  - '@capacitor/cli@8.5.1'
  - '@capacitor/core@8.5.1'
  - '@capacitor/ios@8.5.1'
  - '@tiptap/core@3.31.0'
  - '@tiptap/extension-blockquote@3.31.0'
  - '@tiptap/extension-bold@3.31.0'
  - '@tiptap/extension-code@3.31.0'
  - '@tiptap/extension-document@3.31.0'
  - '@tiptap/extension-hard-break@3.31.0'
  - '@tiptap/extension-heading@3.31.0'
  - '@tiptap/extension-italic@3.31.0'
  - '@tiptap/extension-link@3.31.0'
  - '@tiptap/extension-list@3.31.0'
  - '@tiptap/extension-paragraph@3.31.0'
  - '@tiptap/extension-text@3.31.0'
  - '@tiptap/extensions@3.31.0'
  - '@tiptap/pm@3.31.0'
  - '@typescript-eslint/eslint-plugin@8.69.0'
  - '@typescript-eslint/parser@8.69.0'
  - '@typescript-eslint/project-service@8.69.0'
  - '@typescript-eslint/scope-manager@8.69.0'
  - '@typescript-eslint/tsconfig-utils@8.69.0'
  - '@typescript-eslint/type-utils@8.69.0'
  - '@typescript-eslint/types@8.69.0'
  - '@typescript-eslint/typescript-estree@8.69.0'
  - '@typescript-eslint/utils@8.69.0'
  - '@typescript-eslint/visitor-keys@8.69.0'
  - typescript-eslint@8.69.0
